//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcIndep_Carpeta.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Ariamevadb-svr\\va_data$\\Pacientes")]
        public string PathPacientes {
            get {
                return ((string)(this["PathPacientes"]));
            }
            set {
                this["PathPacientes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\FISICA0\\isos")]
        public string PathIsos {
            get {
                return ((string)(this["PathIsos"]));
            }
            set {
                this["PathIsos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\FISICA0\\isos\\Copias de patmove")]
        public string PathCopiaIsos {
            get {
                return ((string)(this["PathCopiaIsos"]));
            }
            set {
                this["PathCopiaIsos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ARIAMEVADB-SVR\\va_data$\\Calculo Independiente")]
        public string PathPrograma {
            get {
                return ((string)(this["PathPrograma"]));
            }
            set {
                this["PathPrograma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ARIAMEVADB-SVR\\va_data$\\Export")]
        public string PathDCMRP {
            get {
                return ((string)(this["PathDCMRP"]));
            }
            set {
                this["PathDCMRP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Fisica0\\dicom rt")]
        public string PathDCMEquipo {
            get {
                return ((string)(this["PathDCMEquipo"]));
            }
            set {
                this["PathDCMEquipo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\FISICA0\\equipo2\\DICOM RT")]
        public string PathDCMEquipo2 {
            get {
                return ((string)(this["PathDCMEquipo2"]));
            }
            set {
                this["PathDCMEquipo2"] = value;
            }
        }
    }
}
